import type { Product } from '../types';

export const products: Product[] = [
  { id: 'prod-1', name: 'Libro de Historia', description: 'Edición ilustrada de historia latinoamericana.', price: 28, currency: 'USD', inventory: 12, type: 'book', tags: ['historia', 'libro'], image: 'images/products/prod-01.webp' },
  { id: 'prod-2', name: 'Póster Cultural', description: 'Póster artístico con un mapa cultural para tu espacio.', price: 18, currency: 'USD', inventory: 8, type: 'print', tags: ['arte', 'póster'], image: 'images/products/prod-02.webp' },
  { id: 'prod-3', name: 'Caja de Té', description: 'Selección de té artesanal de sabores locales.', price: 14, currency: 'USD', inventory: 20, type: 'music', tags: ['artesanal', 'experiencia'], image: 'images/products/prod-03.webp' },
  { id: 'prod-4', name: 'Suscripción Campaña', description: 'Acceso a campañas culturales y contenido exclusivo.', price: 35, currency: 'USD', inventory: 50, type: 'movie', tags: ['suscripción', 'cultura'], image: 'images/products/prod-04.webp' },
  { id: 'prod-5', name: 'Antología de Poesía Andina', description: 'Selección bilingüe de voces contemporáneas de los Andes.', price: 22, currency: 'USD', inventory: 18, type: 'book', tags: ['poesía', 'andina', 'literatura'], image: 'images/products/prod-05.webp' },
  { id: 'prod-6', name: 'Cuaderno de Arte Popular', description: 'Cuaderno ilustrado para registrar ideas, bocetos y memorias de viaje.', price: 12, currency: 'USD', inventory: 30, type: 'book', tags: ['papelería', 'arte', 'diseño'], image: 'images/products/prod-06.webp' },
  { id: 'prod-7', name: 'Vinilo Raíces del Altiplano', description: 'Edición en vinilo de música instrumental inspirada en ritmos tradicionales.', price: 32, currency: 'USD', inventory: 9, type: 'music', tags: ['vinilo', 'folclore', 'música'], image: 'images/products/prod-07.webp' },
  { id: 'prod-8', name: 'Sesión Acústica del Sur', description: 'Descarga digital de un concierto acústico de artistas emergentes.', price: 9, currency: 'USD', inventory: 99, type: 'music', tags: ['digital', 'concierto', 'independiente'], image: 'images/products/prod-08.webp' },
  { id: 'prod-9', name: 'Cine de Barrio: Colección 1', description: 'Selección curada de cortometrajes latinoamericanos con material de contexto.', price: 19, currency: 'USD', inventory: 15, type: 'movie', tags: ['cine', 'cortometrajes', 'latinoamérica'], image: 'images/products/prod-09.webp' },
  { id: 'prod-10', name: 'Documental Oficios Vivos', description: 'Documental sobre técnicas y saberes de artesanas y artesanos locales.', price: 16, currency: 'USD', inventory: 25, type: 'movie', tags: ['documental', 'oficios', 'comunidad'], image: 'images/products/prod-10.webp' },
  { id: 'prod-11', name: 'Serigrafía Mercado Central', description: 'Impresión serigráfica numerada de una escena cotidiana del mercado.', price: 26, currency: 'USD', inventory: 10, type: 'print', tags: ['serigrafía', 'urbano', 'edición limitada'], image: 'images/products/prod-11.webp' },
  { id: 'prod-12', name: 'Lámina Flora Nativa', description: 'Lámina botánica impresa en papel de algodón, lista para enmarcar.', price: 20, currency: 'USD', inventory: 22, type: 'print', tags: ['botánica', 'ilustración', 'hogar'], image: 'images/products/prod-12.webp' },
  { id: 'prod-13', name: 'Acuarela Viento del Valle', description: 'Acuarela original en pequeño formato inspirada en los valles interandinos.', price: 85, currency: 'USD', inventory: 3, type: 'painting', tags: ['acuarela', 'original', 'paisaje'], image: 'images/products/prod-13.webp' },
  { id: 'prod-14', name: 'Óleo Nocturno Urbano', description: 'Pintura al óleo de arquitectura nocturna y luces de ciudad.', price: 140, currency: 'USD', inventory: 2, type: 'painting', tags: ['óleo', 'ciudad', 'original'], image: 'images/products/prod-14.webp' },
  { id: 'prod-15', name: 'Escultura Semilla', description: 'Pieza de cerámica modelada a mano con acabado mate natural.', price: 48, currency: 'USD', inventory: 7, type: 'sculpture', tags: ['cerámica', 'hecho a mano', 'decoración'], image: 'images/products/prod-15.webp' },
  { id: 'prod-16', name: 'Figura de Madera Tallada', description: 'Escultura de madera recuperada, tallada y sellada por artistas locales.', price: 62, currency: 'USD', inventory: 5, type: 'sculpture', tags: ['madera', 'tallado', 'artesanía'], image: 'images/products/prod-16.webp' },
  { id: 'prod-17', name: 'Libro Cocina y Memoria', description: 'Recetas familiares acompañadas de relatos de migración y encuentro.', price: 24, currency: 'USD', inventory: 16, type: 'book', tags: ['cocina', 'memoria', 'recetas'], image: 'images/products/prod-17.webp' },
  { id: 'prod-18', name: 'Póster Festival de Cine', description: 'Afiche conmemorativo de festival, impreso en tinta vegetal.', price: 17, currency: 'USD', inventory: 14, type: 'print', tags: ['cine', 'afiche', 'coleccionable'], image: 'images/products/prod-18.webp' },
  { id: 'prod-19', name: 'EP Voces del Río', description: 'Edición digital de cinco canciones creadas junto a comunidades ribereñas.', price: 8, currency: 'USD', inventory: 99, type: 'music', tags: ['ep', 'música', 'comunidad'], image: 'images/products/prod-19.webp' },
  { id: 'prod-20', name: 'Fotolibro Ciudades Vivas', description: 'Fotografías de barrios, oficios y encuentros cotidianos en América Latina.', price: 29, currency: 'USD', inventory: 11, type: 'book', tags: ['fotografía', 'ciudad', 'memoria'], image: 'images/products/prod-20.webp' },
];
